//
//  StyleConfiguration.m
//  Style
//
//  Created by chengfj on 16/3/23.
//  Copyright (c) 2016 Chengfj. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleConfiguration.h"


@implementation StyleConfiguration

#pragma mark Cache

static UIColor* _tintColor = nil;
static UIColor* _textColor3 = nil;
static UIColor* _textColor6 = nil;
static UIColor* _textColor9 = nil;
static UIColor* _lineColor = nil;
static UIColor* _backgroundDefaultColor = nil;
static UIColor* _buttonBgColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _tintColor = [UIColor colorWithRed: 0.059 green: 0.573 blue: 0.843 alpha: 1];
    _textColor3 = [UIColor colorWithRed: 0.2 green: 0.2 blue: 0.2 alpha: 1];
    _textColor6 = [UIColor colorWithRed: 0.4 green: 0.4 blue: 0.4 alpha: 1];
    _textColor9 = [UIColor colorWithRed: 0.6 green: 0.6 blue: 0.6 alpha: 1];
    _lineColor = [UIColor colorWithRed: 0.914 green: 0.914 blue: 0.914 alpha: 1];
    _backgroundDefaultColor = [UIColor colorWithRed: 0.976 green: 0.976 blue: 0.976 alpha: 1];
    _buttonBgColor = [UIColor colorWithRed: 0.102 green: 0.78 blue: 0.933 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)tintColor { return _tintColor; }
+ (UIColor*)textColor3 { return _textColor3; }
+ (UIColor*)textColor6 { return _textColor6; }
+ (UIColor*)textColor9 { return _textColor9; }
+ (UIColor*)lineColor { return _lineColor; }
+ (UIColor*)backgroundDefaultColor { return _backgroundDefaultColor; }
+ (UIColor *)buttonBgColor {return _buttonBgColor; }

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
}

@end
