//
//  StyleConfiguration.h
//  Style
//
//  Created by chengfj on 16/3/23.
//  Copyright (c) 2016 Chengfj. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleConfiguration : NSObject

// Colors
+ (UIColor*)tintColor;
+ (UIColor*)textColor3;
+ (UIColor*)textColor6;
+ (UIColor*)textColor9;
+ (UIColor*)lineColor;
+ (UIColor*)backgroundDefaultColor;
+ (UIColor*)buttonBgColor;

// Drawing Methods
+ (void)drawCanvas1;

@end
